require("dotenv").config();
const mongoose = require("mongoose");
const { Movie } = require("../models/models");

// Schema: { Title, Description, Genre: { Name, Description }, Director: { Name, Bio, Birth }, Actors, ImagePath, Featured }
// ImagePath uses TMDB poster URLs (https://image.tmdb.org/t/p/w500/<poster_path>)
// Re-running is safe — upserts by Title.

const movies = [

  // ── Marvel Cinematic Universe (Phase 1–5) ────────────────────────────────
  {
    Title: "Iron Man",
    Description: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Jon Favreau", Bio: "American actor and filmmaker known for directing the first two Iron Man films.", Birth: "October 19, 1966, in New York City, New York, USA" },
    Actors: ["Robert Downey Jr.", "Jeff Bridges", "Gwyneth Paltrow"],
    ImagePath: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBBS0D9OBN.jpg",
    Featured: true,
  },
  {
    Title: "The Incredible Hulk",
    Description: "Bruce Banner, a scientist on the run from the U.S. Government, must find a cure for the monster he emerges whenever he loses his temper.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Louis Leterrier", Bio: "French filmmaker known for action-driven blockbusters.", Birth: "June 17, 1973, in Paris, France" },
    Actors: ["Edward Norton", "Liv Tyler", "Tim Roth"],
    ImagePath: "https://image.tmdb.org/t/p/w500/gLFzWXS5XUkUFjAsMqj2CqQhpOd.jpg",
    Featured: false,
  },
  {
    Title: "Iron Man 2",
    Description: "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father's legacy.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Jon Favreau", Bio: "American actor and filmmaker known for directing the first two Iron Man films.", Birth: "October 19, 1966, in New York City, New York, USA" },
    Actors: ["Robert Downey Jr.", "Mickey Rourke", "Gwyneth Paltrow"],
    ImagePath: "https://image.tmdb.org/t/p/w500/6WBeq4tCgG45MnIX6PiY5gKoJaV.jpg",
    Featured: false,
  },
  {
    Title: "Thor",
    Description: "The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard, where he soon becomes one of their finest defenders.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Kenneth Branagh", Bio: "British actor and filmmaker celebrated for Shakespearean adaptations.", Birth: "December 10, 1960, in Belfast, Northern Ireland" },
    Actors: ["Chris Hemsworth", "Natalie Portman", "Tom Hiddleston"],
    ImagePath: "https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh2xMaYEO.jpg",
    Featured: false,
  },
  {
    Title: "Captain America: The First Avenger",
    Description: "Steve Rogers, a rejected military soldier, transforms into Captain America after taking a dose of a Super-Soldier serum. But being Captain America comes at a price.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Joe Johnston", Bio: "American filmmaker and visual effects artist.", Birth: "May 13, 1950, in Austin, Texas, USA" },
    Actors: ["Chris Evans", "Hugo Weaving", "Hayley Atwell"],
    ImagePath: "https://image.tmdb.org/t/p/w500/vSNxpHkTpjzHQFIjX6T7bIi4rD5.jpg",
    Featured: false,
  },
  {
    Title: "The Avengers",
    Description: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki from enslaving humanity.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Joss Whedon", Bio: "American screenwriter, director, and producer behind Buffy and Firefly.", Birth: "June 23, 1964, in New York City, New York, USA" },
    Actors: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
    ImagePath: "https://image.tmdb.org/t/p/w500/cezWGskPY5x7GaglTTRN4Fugfb8.jpg",
    Featured: true,
  },
  {
    Title: "Iron Man 3",
    Description: "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Shane Black", Bio: "American filmmaker and screenwriter who created the Lethal Weapon franchise.", Birth: "December 16, 1961, in Pittsburgh, Pennsylvania, USA" },
    Actors: ["Robert Downey Jr.", "Gwyneth Paltrow", "Ben Kingsley"],
    ImagePath: "https://image.tmdb.org/t/p/w500/qhRex189iu6QFhJCkJPwi2G8TqM.jpg",
    Featured: false,
  },
  {
    Title: "Thor: The Dark World",
    Description: "When the Dark Elves attempt to plunge the universe into darkness, Thor must embark on a perilous and personal journey that reunites him with doctor Jane Foster.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Alan Taylor", Bio: "American filmmaker known for his work on Game of Thrones.", Birth: "October 24, 1959, in Cannes, France" },
    Actors: ["Chris Hemsworth", "Natalie Portman", "Tom Hiddleston"],
    ImagePath: "https://image.tmdb.org/t/p/w500/bnX5PqConnz4iS8lDFBqQANEfap.jpg",
    Featured: false,
  },
  {
    Title: "Captain America: The Winter Soldier",
    Description: "As Steve Rogers struggles to embrace his role in the modern world, he teams up with Black Widow to battle a new threat from old history.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Anthony Russo", Bio: "American filmmaker who, with brother Joe Russo, directed the climactic Avengers films.", Birth: "February 3, 1970, in Cleveland, Ohio, USA" },
    Actors: ["Chris Evans", "Scarlett Johansson", "Samuel L. Jackson"],
    ImagePath: "https://image.tmdb.org/t/p/w500/5TQ6JkKGMN1ynVYteHAUFMDRNhz.jpg",
    Featured: true,
  },
  {
    Title: "Guardians of the Galaxy",
    Description: "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "James Gunn", Bio: "American filmmaker and writer who also helmed the DC Universe reboot.", Birth: "August 5, 1966, in St. Louis, Missouri, USA" },
    Actors: ["Chris Pratt", "Zoe Saldana", "Dave Bautista"],
    ImagePath: "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
    Featured: true,
  },
  {
    Title: "Avengers: Age of Ultron",
    Description: "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and Earth's mightiest heroes are put to the ultimate test.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Joss Whedon", Bio: "American screenwriter, director, and producer behind Buffy and Firefly.", Birth: "June 23, 1964, in New York City, New York, USA" },
    Actors: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    ImagePath: "https://image.tmdb.org/t/p/w500/t90Y3G8UGQp0f0DrP60wRu9fozX.jpg",
    Featured: false,
  },
  {
    Title: "Ant-Man",
    Description: "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Peyton Reed", Bio: "American filmmaker known for comedies and the Ant-Man series.", Birth: "July 3, 1964, in Raleigh, North Carolina, USA" },
    Actors: ["Paul Rudd", "Michael Douglas", "Evangeline Lilly"],
    ImagePath: "https://image.tmdb.org/t/p/w500/kMRVN0K9ddWFbBFLzCJFzHBmAlw.jpg",
    Featured: false,
  },
  {
    Title: "Captain America: Civil War",
    Description: "Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Anthony Russo", Bio: "American filmmaker who, with brother Joe Russo, directed the climactic Avengers films.", Birth: "February 3, 1970, in Cleveland, Ohio, USA" },
    Actors: ["Chris Evans", "Robert Downey Jr.", "Scarlett Johansson"],
    ImagePath: "https://image.tmdb.org/t/p/w500/rAGiXaUfDiyHtEp5iOCPDMrNqzm.jpg",
    Featured: true,
  },
  {
    Title: "Doctor Strange",
    Description: "A former neurosurgeon embarks on a journey of healing only to be drawn into the world of the mystic arts.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Scott Derrickson", Bio: "American filmmaker specializing in horror and supernatural thrillers.", Birth: "July 15, 1966, in Denver, Colorado, USA" },
    Actors: ["Benedict Cumberbatch", "Chiwetel Ejiofor", "Rachel McAdams"],
    ImagePath: "https://image.tmdb.org/t/p/w500/uGBVAWjjA55V6UJune3ZNDHeYGz.jpg",
    Featured: false,
  },
  {
    Title: "Guardians of the Galaxy Vol. 2",
    Description: "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "James Gunn", Bio: "American filmmaker and writer who also helmed the DC Universe reboot.", Birth: "August 5, 1966, in St. Louis, Missouri, USA" },
    Actors: ["Chris Pratt", "Zoe Saldana", "Dave Bautista"],
    ImagePath: "https://image.tmdb.org/t/p/w500/y4MBh0EjBlMuOzv9axM4eW9GFOH.jpg",
    Featured: false,
  },
  {
    Title: "Spider-Man: Homecoming",
    Description: "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Jon Watts", Bio: "American filmmaker who directed the MCU Spider-Man trilogy.", Birth: "June 28, 1981, in Fountain, Colorado, USA" },
    Actors: ["Tom Holland", "Michael Keaton", "Robert Downey Jr."],
    ImagePath: "https://image.tmdb.org/t/p/w500/c24sv2weTHPsmDa7jEMN0kzOkm8.jpg",
    Featured: false,
  },
  {
    Title: "Thor: Ragnarok",
    Description: "Thor is imprisoned on the planet Sakaar, and must race against time to return to Asgard and stop Ragnarök.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Taika Waititi", Bio: "New Zealand filmmaker and actor celebrated for quirky, heartfelt comedies.", Birth: "August 16, 1975, in Raukokore, New Zealand" },
    Actors: ["Chris Hemsworth", "Tom Hiddleston", "Cate Blanchett"],
    ImagePath: "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    Featured: true,
  },
  {
    Title: "Black Panther",
    Description: "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Ryan Coogler", Bio: "American filmmaker known for Fruitvale Station, Creed, and Black Panther.", Birth: "May 23, 1986, in Oakland, California, USA" },
    Actors: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o"],
    ImagePath: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    Featured: true,
  },
  {
    Title: "Avengers: Infinity War",
    Description: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Anthony Russo", Bio: "American filmmaker who, with brother Joe Russo, directed the climactic Avengers films.", Birth: "February 3, 1970, in Cleveland, Ohio, USA" },
    Actors: ["Robert Downey Jr.", "Chris Hemsworth", "Josh Brolin"],
    ImagePath: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    Featured: true,
  },
  {
    Title: "Ant-Man and the Wasp",
    Description: "As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Peyton Reed", Bio: "American filmmaker known for comedies and the Ant-Man series.", Birth: "July 3, 1964, in Raleigh, North Carolina, USA" },
    Actors: ["Paul Rudd", "Evangeline Lilly", "Michael Douglas"],
    ImagePath: "https://image.tmdb.org/t/p/w500/9iP1pyJitTbQk6qumXjGE15rRuF.jpg",
    Featured: false,
  },
  {
    Title: "Avengers: Endgame",
    Description: "After the devastating events of Infinity War, the universe is in ruins. The Avengers assemble once more to reverse Thanos's actions and restore balance.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Anthony Russo", Bio: "American filmmaker who, with brother Joe Russo, directed the climactic Avengers films.", Birth: "February 3, 1970, in Cleveland, Ohio, USA" },
    Actors: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    ImagePath: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    Featured: true,
  },
  {
    Title: "Spider-Man: Far From Home",
    Description: "Following the events of Avengers: Endgame, Spider-Man must step up to take on new threats in a world that has changed forever.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Jon Watts", Bio: "American filmmaker who directed the MCU Spider-Man trilogy.", Birth: "June 28, 1981, in Fountain, Colorado, USA" },
    Actors: ["Tom Holland", "Samuel L. Jackson", "Zendaya"],
    ImagePath: "https://image.tmdb.org/t/p/w500/lcq8dVxeeOqHvvgcte707K0KjDf.jpg",
    Featured: false,
  },
  {
    Title: "Black Widow",
    Description: "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Cate Shortland", Bio: "Australian filmmaker known for intimate character-driven dramas.", Birth: "April 10, 1968, in Bombala, New South Wales, Australia" },
    Actors: ["Scarlett Johansson", "Florence Pugh", "David Harbour"],
    ImagePath: "https://image.tmdb.org/t/p/w500/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
    Featured: false,
  },
  {
    Title: "Shang-Chi and the Legend of the Ten Rings",
    Description: "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Destin Daniel Cretton", Bio: "American filmmaker known for Short Term 12 and Just Mercy.", Birth: "August 10, 1978, in Maui, Hawaii, USA" },
    Actors: ["Simu Liu", "Tony Leung", "Awkwafina"],
    ImagePath: "https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
    Featured: false,
  },
  {
    Title: "Eternals",
    Description: "The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Chloé Zhao", Bio: "Chinese-American filmmaker and Academy Award winner for Nomadland.", Birth: "March 31, 1982, in Beijing, China" },
    Actors: ["Gemma Chan", "Richard Madden", "Angelina Jolie"],
    ImagePath: "https://image.tmdb.org/t/p/w500/bcCBq9N1EMo3daNbbe1TXKieJly.jpg",
    Featured: false,
  },
  {
    Title: "Spider-Man: No Way Home",
    Description: "With Spider-Man's identity now revealed, Peter Parker asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Jon Watts", Bio: "American filmmaker who directed the MCU Spider-Man trilogy.", Birth: "June 28, 1981, in Fountain, Colorado, USA" },
    Actors: ["Tom Holland", "Zendaya", "Benedict Cumberbatch"],
    ImagePath: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    Featured: true,
  },
  {
    Title: "Doctor Strange in the Multiverse of Madness",
    Description: "Doctor Strange teams up with a mysterious Chavez to travel the Multiverse and face a powerful adversary determined to obtain Chavez's power.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Sam Raimi", Bio: "American filmmaker celebrated for the Evil Dead franchise and original Spider-Man trilogy.", Birth: "October 23, 1959, in Royal Oak, Michigan, USA" },
    Actors: ["Benedict Cumberbatch", "Elizabeth Olsen", "Rachel McAdams"],
    ImagePath: "https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
    Featured: false,
  },
  {
    Title: "Thor: Love and Thunder",
    Description: "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Taika Waititi", Bio: "New Zealand filmmaker and actor celebrated for quirky, heartfelt comedies.", Birth: "August 16, 1975, in Raukokore, New Zealand" },
    Actors: ["Chris Hemsworth", "Natalie Portman", "Christian Bale"],
    ImagePath: "https://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    Featured: false,
  },
  {
    Title: "Black Panther: Wakanda Forever",
    Description: "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T'Challa.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Ryan Coogler", Bio: "American filmmaker known for Fruitvale Station, Creed, and Black Panther.", Birth: "May 23, 1986, in Oakland, California, USA" },
    Actors: ["Letitia Wright", "Lupita Nyong'o", "Danai Gurira"],
    ImagePath: "https://image.tmdb.org/t/p/w500/sv1xJUazXoQuIDTIL6rLMGE8Nez.jpg",
    Featured: false,
  },
  {
    Title: "Ant-Man and the Wasp: Quantumania",
    Description: "Scott Lang and Hope Van Dyne are pulled into the Quantum Realm along with Hope's parents and Scott's daughter Cassie, who must now battle Kang the Conqueror.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Peyton Reed", Bio: "American filmmaker known for comedies and the Ant-Man series.", Birth: "July 3, 1964, in Raleigh, North Carolina, USA" },
    Actors: ["Paul Rudd", "Evangeline Lilly", "Jonathan Majors"],
    ImagePath: "https://image.tmdb.org/t/p/w500/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
    Featured: false,
  },
  {
    Title: "Guardians of the Galaxy Vol. 3",
    Description: "Still reeling from the loss of Gamora, Peter Quill must rally his team around him to defend the universe and protect one of their own.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "James Gunn", Bio: "American filmmaker and writer who also helmed the DC Universe reboot.", Birth: "August 5, 1966, in St. Louis, Missouri, USA" },
    Actors: ["Chris Pratt", "Zoe Saldana", "Dave Bautista"],
    ImagePath: "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    Featured: false,
  },

  // ── The Dark Knight Trilogy ────────────────────────────────────────────────
  {
    Title: "Batman Begins",
    Description: "After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Christopher Nolan", Bio: "British-American filmmaker renowned for complex, cerebral blockbusters.", Birth: "July 30, 1970, in London, England, UK" },
    Actors: ["Christian Bale", "Liam Neeson", "Katie Holmes"],
    ImagePath: "https://image.tmdb.org/t/p/w500/8RW2runSEc34IwKN2D1aPcJd2UL.jpg",
    Featured: false,
  },
  {
    Title: "The Dark Knight",
    Description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Christopher Nolan", Bio: "British-American filmmaker renowned for complex, cerebral blockbusters.", Birth: "July 30, 1970, in London, England, UK" },
    Actors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    ImagePath: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    Featured: true,
  },
  {
    Title: "The Dark Knight Rises",
    Description: "Eight years after the Joker's reign of anarchy, Batman is forced from his exile to defend Gotham City from the brutal guerrilla terrorist Bane.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Christopher Nolan", Bio: "British-American filmmaker renowned for complex, cerebral blockbusters.", Birth: "July 30, 1970, in London, England, UK" },
    Actors: ["Christian Bale", "Tom Hardy", "Anne Hathaway"],
    ImagePath: "https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn41nA.jpg",
    Featured: false,
  },

  // ── Star Wars (Skywalker Saga + Spinoffs) ─────────────────────────────────
  {
    Title: "Star Wars: The Phantom Menace",
    Description: "Two Jedi Knights escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to claim their old glory.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "George Lucas", Bio: "American filmmaker and entrepreneur who created the Star Wars and Indiana Jones franchises.", Birth: "May 14, 1944, in Modesto, California, USA" },
    Actors: ["Liam Neeson", "Ewan McGregor", "Natalie Portman"],
    ImagePath: "https://image.tmdb.org/t/p/w500/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg",
    Featured: false,
  },
  {
    Title: "Star Wars: Attack of the Clones",
    Description: "Ten years after initially meeting, Anakin Skywalker shares a forbidden romance with Padmé Amidala while Obi-Wan Kenobi investigates an assassination attempt on the senator.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "George Lucas", Bio: "American filmmaker and entrepreneur who created the Star Wars and Indiana Jones franchises.", Birth: "May 14, 1944, in Modesto, California, USA" },
    Actors: ["Ewan McGregor", "Natalie Portman", "Hayden Christensen"],
    ImagePath: "https://image.tmdb.org/t/p/w500/56sblWpBCfBjS62g5omRRCnKNSe.jpg",
    Featured: false,
  },
  {
    Title: "Star Wars: Revenge of the Sith",
    Description: "As the war between the Jedi and Separatists comes to an end, Anakin Skywalker is seduced by the dark side of the Force to become the Sith lord Darth Vader.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "George Lucas", Bio: "American filmmaker and entrepreneur who created the Star Wars and Indiana Jones franchises.", Birth: "May 14, 1944, in Modesto, California, USA" },
    Actors: ["Ewan McGregor", "Hayden Christensen", "Natalie Portman"],
    ImagePath: "https://image.tmdb.org/t/p/w500/9PEPcTrHMSjDSqMVBEiDNNYfQ34.jpg",
    Featured: false,
  },
  {
    Title: "Star Wars: A New Hope",
    Description: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire's world-destroying battle station.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "George Lucas", Bio: "American filmmaker and entrepreneur who created the Star Wars and Indiana Jones franchises.", Birth: "May 14, 1944, in Modesto, California, USA" },
    Actors: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    ImagePath: "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    Featured: true,
  },
  {
    Title: "Star Wars: The Empire Strikes Back",
    Description: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Irvin Kershner", Bio: "American film director best known for The Empire Strikes Back.", Birth: "April 29, 1923, in Philadelphia, Pennsylvania, USA" },
    Actors: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    ImagePath: "https://image.tmdb.org/t/p/w500/2l05cFWJacyIsTpsqSgH0wQXe4V.jpg",
    Featured: true,
  },
  {
    Title: "Star Wars: Return of the Jedi",
    Description: "After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Richard Marquand", Bio: "Welsh filmmaker who directed Return of the Jedi under George Lucas's guidance.", Birth: "September 22, 1937, in Cardiff, Wales, UK" },
    Actors: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    ImagePath: "https://image.tmdb.org/t/p/w500/mDCBQNhR6R0PVFucJlU3CGHMFXG.jpg",
    Featured: false,
  },
  {
    Title: "Rogue One: A Star Wars Story",
    Description: "The daughter of an Imperial scientist joins a motley crew of rebels on a mission to steal the plans for the Death Star.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Gareth Edwards", Bio: "British filmmaker known for Monsters and the Godzilla reboot.", Birth: "June 1, 1975, in Nuneaton, Warwickshire, England, UK" },
    Actors: ["Felicity Jones", "Diego Luna", "Ben Mendelsohn"],
    ImagePath: "https://image.tmdb.org/t/p/w500/i0yw1mFbB7sNGHCs7EXZPzFkdA1.jpg",
    Featured: false,
  },
  {
    Title: "Star Wars: The Force Awakens",
    Description: "As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "J.J. Abrams", Bio: "American filmmaker and producer behind the Mission: Impossible and Star Trek reboots.", Birth: "June 27, 1966, in New York City, New York, USA" },
    Actors: ["Daisy Ridley", "John Boyega", "Oscar Isaac"],
    ImagePath: "https://image.tmdb.org/t/p/w500/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg",
    Featured: false,
  },
  {
    Title: "Solo: A Star Wars Story",
    Description: "During an adventure into a dark criminal underworld, Han Solo meets his mighty future co-pilot Chewbacca and encounters the notorious gambler Lando Calrissian.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Ron Howard", Bio: "American filmmaker and actor celebrated for Apollo 13, A Beautiful Mind, and more.", Birth: "March 1, 1954, in Duncan, Oklahoma, USA" },
    Actors: ["Alden Ehrenreich", "Woody Harrelson", "Emilia Clarke"],
    ImagePath: "https://image.tmdb.org/t/p/w500/3oAa8mJJ97CH9AeGEY6vjAxqcvZ.jpg",
    Featured: false,
  },
  {
    Title: "Star Wars: The Last Jedi",
    Description: "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Rian Johnson", Bio: "American filmmaker celebrated for Looper and Knives Out.", Birth: "December 17, 1973, in Silver City, New Mexico, USA" },
    Actors: ["Daisy Ridley", "John Boyega", "Mark Hamill"],
    ImagePath: "https://image.tmdb.org/t/p/w500/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
    Featured: false,
  },
  {
    Title: "Star Wars: The Rise of Skywalker",
    Description: "The surviving Resistance faces the First Order once more as Rey, Finn and Poe Dameron's journey continues.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "J.J. Abrams", Bio: "American filmmaker and producer behind the Mission: Impossible and Star Trek reboots.", Birth: "June 27, 1966, in New York City, New York, USA" },
    Actors: ["Daisy Ridley", "Adam Driver", "John Boyega"],
    ImagePath: "https://image.tmdb.org/t/p/w500/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
    Featured: false,
  },

  // ── The Lord of the Rings ──────────────────────────────────────────────────
  {
    Title: "The Lord of the Rings: The Fellowship of the Ring",
    Description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "Peter Jackson", Bio: "New Zealand filmmaker celebrated for the Lord of the Rings and Hobbit trilogies.", Birth: "October 31, 1961, in Pukerua Bay, New Zealand" },
    Actors: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
    ImagePath: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    Featured: true,
  },
  {
    Title: "The Lord of the Rings: The Two Towers",
    Description: "While Frodo and Samwise edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "Peter Jackson", Bio: "New Zealand filmmaker celebrated for the Lord of the Rings and Hobbit trilogies.", Birth: "October 31, 1961, in Pukerua Bay, New Zealand" },
    Actors: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
    ImagePath: "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYspV.jpg",
    Featured: false,
  },
  {
    Title: "The Lord of the Rings: The Return of the King",
    Description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "Peter Jackson", Bio: "New Zealand filmmaker celebrated for the Lord of the Rings and Hobbit trilogies.", Birth: "October 31, 1961, in Pukerua Bay, New Zealand" },
    Actors: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"],
    ImagePath: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    Featured: true,
  },

  // ── The Hobbit Trilogy ────────────────────────────────────────────────────
  {
    Title: "The Hobbit: An Unexpected Journey",
    Description: "A reluctant Hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home — and the gold within it — from the dragon Smaug.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "Peter Jackson", Bio: "New Zealand filmmaker celebrated for the Lord of the Rings and Hobbit trilogies.", Birth: "October 31, 1961, in Pukerua Bay, New Zealand" },
    Actors: ["Martin Freeman", "Ian McKellen", "Richard Armitage"],
    ImagePath: "https://image.tmdb.org/t/p/w500/xSCk04vvTuISzPHdXeJ3eknptUO.jpg",
    Featured: false,
  },
  {
    Title: "The Hobbit: The Desolation of Smaug",
    Description: "The dwarves, along with Bilbo Baggins and Gandalf the Grey, continue their quest to reclaim Erebor from Smaug.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "Peter Jackson", Bio: "New Zealand filmmaker celebrated for the Lord of the Rings and Hobbit trilogies.", Birth: "October 31, 1961, in Pukerua Bay, New Zealand" },
    Actors: ["Martin Freeman", "Ian McKellen", "Richard Armitage"],
    ImagePath: "https://image.tmdb.org/t/p/w500/xT98tLqatZPQApZTGLFFSHDzuXM.jpg",
    Featured: false,
  },
  {
    Title: "The Hobbit: The Battle of the Five Armies",
    Description: "Bilbo and Company are forced to engage in a war against an array of combatants and keep the Lonely Mountain from falling into the hands of a rising darkness.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "Peter Jackson", Bio: "New Zealand filmmaker celebrated for the Lord of the Rings and Hobbit trilogies.", Birth: "October 31, 1961, in Pukerua Bay, New Zealand" },
    Actors: ["Martin Freeman", "Ian McKellen", "Richard Armitage"],
    ImagePath: "https://image.tmdb.org/t/p/w500/jF3OtKLFO8bEIHMFsWs7QlRTenw.jpg",
    Featured: false,
  },

  // ── Harry Potter (All 8) ──────────────────────────────────────────────────
  {
    Title: "Harry Potter and the Sorcerer's Stone",
    Description: "An orphaned boy discovers he is a wizard and enrolls in Hogwarts School of Witchcraft and Wizardry, where he learns the truth about his parents' death.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "Chris Columbus", Bio: "American filmmaker who launched the Harry Potter and Home Alone franchises.", Birth: "September 10, 1958, in Spangler, Pennsylvania, USA" },
    Actors: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
    ImagePath: "https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
    Featured: false,
  },
  {
    Title: "Harry Potter and the Chamber of Secrets",
    Description: "An ancient prophecy seems to be coming true when a mysterious presence begins stalking the corridors of a school of magic and leaving its victims paralyzed.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "Chris Columbus", Bio: "American filmmaker who launched the Harry Potter and Home Alone franchises.", Birth: "September 10, 1958, in Spangler, Pennsylvania, USA" },
    Actors: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
    ImagePath: "https://image.tmdb.org/t/p/w500/sdEExFivaiGMTCDVWIYnHs6XvVT.jpg",
    Featured: false,
  },
  {
    Title: "Harry Potter and the Prisoner of Azkaban",
    Description: "It's Harry's third year at Hogwarts; not only does he have a new Defense Against the Dark Arts teacher, but there is also trouble brewing as an escaped prisoner is on the loose.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "Alfonso Cuarón", Bio: "Mexican filmmaker and Academy Award winner for Gravity and Roma.", Birth: "November 28, 1961, in Mexico City, Mexico" },
    Actors: ["Daniel Radcliffe", "Emma Watson", "Gary Oldman"],
    ImagePath: "https://image.tmdb.org/t/p/w500/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg",
    Featured: false,
  },
  {
    Title: "Harry Potter and the Goblet of Fire",
    Description: "Harry Potter finds himself mysteriously selected as an underage competitor in a treacherous tournament between three schools of magic.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "Mike Newell", Bio: "British filmmaker known for Four Weddings and a Funeral.", Birth: "March 28, 1942, in St. Albans, Hertfordshire, England, UK" },
    Actors: ["Daniel Radcliffe", "Emma Watson", "Robert Pattinson"],
    ImagePath: "https://image.tmdb.org/t/p/w500/fECBqHkznvFCmn0aaLZJnNSNOXB.jpg",
    Featured: false,
  },
  {
    Title: "Harry Potter and the Order of the Phoenix",
    Description: "With their warning about Lord Voldemort's return scoffed at, Harry and Dumbledore are targeted by the Ministry of Magic and Harry forms a student defence group.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "David Yates", Bio: "British filmmaker who directed the final four Harry Potter films.", Birth: "October 8, 1963, in St. Helens, Merseyside, England, UK" },
    Actors: ["Daniel Radcliffe", "Emma Watson", "Imelda Staunton"],
    ImagePath: "https://image.tmdb.org/t/p/w500/5aOyriWBkHkMGXCIeW0jDCkqKQg.jpg",
    Featured: false,
  },
  {
    Title: "Harry Potter and the Half-Blood Prince",
    Description: "As Harry Potter begins his sixth year at Hogwarts, he discovers an old book marked as the property of the Half-Blood Prince and begins to learn more about Voldemort's dark past.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "David Yates", Bio: "British filmmaker who directed the final four Harry Potter films.", Birth: "October 8, 1963, in St. Helens, Merseyside, England, UK" },
    Actors: ["Daniel Radcliffe", "Emma Watson", "Jim Broadbent"],
    ImagePath: "https://image.tmdb.org/t/p/w500/z1MV0EOzxBCXe2JJ0OGXMJ0OVIL.jpg",
    Featured: false,
  },
  {
    Title: "Harry Potter and the Deathly Hallows: Part 1",
    Description: "As Harry, Ron, and Hermione race against time and evil to destroy the Horcruxes, they uncover the existence of the three most powerful objects in the wizarding world.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "David Yates", Bio: "British filmmaker who directed the final four Harry Potter films.", Birth: "October 8, 1963, in St. Helens, Merseyside, England, UK" },
    Actors: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
    ImagePath: "https://image.tmdb.org/t/p/w500/maP4MTfPCeVD2FZnKBPMpBgr0Ug.jpg",
    Featured: false,
  },
  {
    Title: "Harry Potter and the Deathly Hallows: Part 2",
    Description: "Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the battle for Hogwarts begins.",
    Genre: { Name: "Fantasy", Description: "Films set in imaginary worlds with magic, myth, and epic adventure." },
    Director: { Name: "David Yates", Bio: "British filmmaker who directed the final four Harry Potter films.", Birth: "October 8, 1963, in St. Helens, Merseyside, England, UK" },
    Actors: ["Daniel Radcliffe", "Emma Watson", "Ralph Fiennes"],
    ImagePath: "https://image.tmdb.org/t/p/w500/Or4KBPbV0WqXRKzRAnXrxfNLLJ.jpg",
    Featured: true,
  },

  // ── Indiana Jones (All 5) ─────────────────────────────────────────────────
  {
    Title: "Raiders of the Lost Ark",
    Description: "In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before the Nazis.",
    Genre: { Name: "Adventure", Description: "Films driven by exploration, discovery, and excitement." },
    Director: { Name: "Steven Spielberg", Bio: "American filmmaker and producer widely regarded as one of the most influential directors in cinema history.", Birth: "December 18, 1946, in Cincinnati, Ohio, USA" },
    Actors: ["Harrison Ford", "Karen Allen", "Paul Freeman"],
    ImagePath: "https://image.tmdb.org/t/p/w500/ceG9VzoRAVGwivFU403Wc3AHRys.jpg",
    Featured: true,
  },
  {
    Title: "Indiana Jones and the Temple of Doom",
    Description: "After arriving in India, Indiana Jones is asked by a desperate village to find a mystical stone and rescue children from a Thugee cult.",
    Genre: { Name: "Adventure", Description: "Films driven by exploration, discovery, and excitement." },
    Director: { Name: "Steven Spielberg", Bio: "American filmmaker and producer widely regarded as one of the most influential directors in cinema history.", Birth: "December 18, 1946, in Cincinnati, Ohio, USA" },
    Actors: ["Harrison Ford", "Kate Capshaw", "Jonathan Ke Quan"],
    ImagePath: "https://image.tmdb.org/t/p/w500/pqxMqTEgc5FwJAXeaFZdBDzRYJA.jpg",
    Featured: false,
  },
  {
    Title: "Indiana Jones and the Last Crusade",
    Description: "In 1938, after his father goes missing while pursuing the Holy Grail, Indiana Jones must find him and prevent the Grail from falling into Nazi hands.",
    Genre: { Name: "Adventure", Description: "Films driven by exploration, discovery, and excitement." },
    Director: { Name: "Steven Spielberg", Bio: "American filmmaker and producer widely regarded as one of the most influential directors in cinema history.", Birth: "December 18, 1946, in Cincinnati, Ohio, USA" },
    Actors: ["Harrison Ford", "Sean Connery", "Alison Doody"],
    ImagePath: "https://image.tmdb.org/t/p/w500/4ZDkPxWNOqFRBMcBHRplNlXt5KR.jpg",
    Featured: false,
  },
  {
    Title: "Indiana Jones and the Kingdom of the Crystal Skull",
    Description: "In 1957, Indiana Jones is thrust back in action, venturing into the jungles of South America to battle Soviet agents after a mysterious crystal skull.",
    Genre: { Name: "Adventure", Description: "Films driven by exploration, discovery, and excitement." },
    Director: { Name: "Steven Spielberg", Bio: "American filmmaker and producer widely regarded as one of the most influential directors in cinema history.", Birth: "December 18, 1946, in Cincinnati, Ohio, USA" },
    Actors: ["Harrison Ford", "Cate Blanchett", "Shia LaBeouf"],
    ImagePath: "https://image.tmdb.org/t/p/w500/7ZCPFLlDXL49bIhcXVXJdBW9AzQ.jpg",
    Featured: false,
  },
  {
    Title: "Indiana Jones and the Dial of Destiny",
    Description: "Archaeologist Indiana Jones races against time to retrieve a legendary dial that can change the course of history.",
    Genre: { Name: "Adventure", Description: "Films driven by exploration, discovery, and excitement." },
    Director: { Name: "James Mangold", Bio: "American filmmaker known for Logan, Walk the Line, and Ford v Ferrari.", Birth: "December 20, 1963, in New York City, New York, USA" },
    Actors: ["Harrison Ford", "Phoebe Waller-Bridge", "Antonio Banderas"],
    ImagePath: "https://image.tmdb.org/t/p/w500/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg",
    Featured: false,
  },

  // ── The Matrix Trilogy ────────────────────────────────────────────────────
  {
    Title: "The Matrix",
    Description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Lana Wachowski", Bio: "American filmmaker and writer, co-creator of The Matrix franchise.", Birth: "June 21, 1965, in Chicago, Illinois, USA" },
    Actors: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    ImagePath: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    Featured: true,
  },
  {
    Title: "The Matrix Reloaded",
    Description: "Freedom fighters Neo, Trinity, and Morpheus lead the revolt against the Machine Army, unlocking the door to the Oracle, the Keymaker and Zion.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Lana Wachowski", Bio: "American filmmaker and writer, co-creator of The Matrix franchise.", Birth: "June 21, 1965, in Chicago, Illinois, USA" },
    Actors: ["Keanu Reeves", "Laurence Fishburne", "Hugo Weaving"],
    ImagePath: "https://image.tmdb.org/t/p/w500/9TBe3J3d5VLQfOxAsWrOneKBJhQ.jpg",
    Featured: false,
  },
  {
    Title: "The Matrix Revolutions",
    Description: "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Lana Wachowski", Bio: "American filmmaker and writer, co-creator of The Matrix franchise.", Birth: "June 21, 1965, in Chicago, Illinois, USA" },
    Actors: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    ImagePath: "https://image.tmdb.org/t/p/w500/ySSBnIKkXqHJFfXBDNblJrJFzqq.jpg",
    Featured: false,
  },
  {
    Title: "The Matrix Resurrections",
    Description: "Return to a world of two realities: one, everyday life; the other, what lies behind it. To find out if his reality is a construct, Neo will have to choose to follow the white rabbit once more.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Lana Wachowski", Bio: "American filmmaker and writer, co-creator of The Matrix franchise.", Birth: "June 21, 1965, in Chicago, Illinois, USA" },
    Actors: ["Keanu Reeves", "Carrie-Anne Moss", "Yahya Abdul-Mateen II"],
    ImagePath: "https://image.tmdb.org/t/p/w500/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
    Featured: false,
  },

  // ── John Wick (All 4) ─────────────────────────────────────────────────────
  {
    Title: "John Wick",
    Description: "An ex-hitman comes out of retirement to track down the gangsters that took everything from him.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Chad Stahelski", Bio: "American stuntman turned filmmaker, known for the John Wick franchise.", Birth: "September 20, 1968, in Worcester, Massachusetts, USA" },
    Actors: ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen"],
    ImagePath: "https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
    Featured: true,
  },
  {
    Title: "John Wick: Chapter 2",
    Description: "After returning to the criminal underworld to repay a debt, John Wick discovers that a large bounty has been put on his life.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Chad Stahelski", Bio: "American stuntman turned filmmaker, known for the John Wick franchise.", Birth: "September 20, 1968, in Worcester, Massachusetts, USA" },
    Actors: ["Keanu Reeves", "Riccardo Scamarcio", "Ian McShane"],
    ImagePath: "https://image.tmdb.org/t/p/w500/hXWBc0ioZP3cN4zCu6sqbeFdUCF.jpg",
    Featured: false,
  },
  {
    Title: "John Wick: Chapter 3 – Parabellum",
    Description: "Super-assassin John Wick is on the run after killing a member of the international assassins' guild, and with a $14 million bounty on his head.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Chad Stahelski", Bio: "American stuntman turned filmmaker, known for the John Wick franchise.", Birth: "September 20, 1968, in Worcester, Massachusetts, USA" },
    Actors: ["Keanu Reeves", "Halle Berry", "Ian McShane"],
    ImagePath: "https://image.tmdb.org/t/p/w500/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg",
    Featured: false,
  },
  {
    Title: "John Wick: Chapter 4",
    Description: "John Wick uncovers a path to defeating the High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Chad Stahelski", Bio: "American stuntman turned filmmaker, known for the John Wick franchise.", Birth: "September 20, 1968, in Worcester, Massachusetts, USA" },
    Actors: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård"],
    ImagePath: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    Featured: true,
  },

  // ── Terminator (Full Series) ──────────────────────────────────────────────
  {
    Title: "The Terminator",
    Description: "A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine programmed to execute a young woman whose unborn son is key to humanity's future.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "James Cameron", Bio: "Canadian filmmaker known for Titanic, Avatar, and the Terminator franchise.", Birth: "August 16, 1954, in Kapuskasing, Ontario, Canada" },
    Actors: ["Arnold Schwarzenegger", "Linda Hamilton", "Michael Biehn"],
    ImagePath: "https://image.tmdb.org/t/p/w500/qvktm0BHcnmDpul4Hz01GIazWPr.jpg",
    Featured: false,
  },
  {
    Title: "Terminator 2: Judgment Day",
    Description: "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son John from a more advanced and powerful cyborg.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "James Cameron", Bio: "Canadian filmmaker known for Titanic, Avatar, and the Terminator franchise.", Birth: "August 16, 1954, in Kapuskasing, Ontario, Canada" },
    Actors: ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong"],
    ImagePath: "https://image.tmdb.org/t/p/w500/weVXMD5QBGeQil4HEATZqFaDSIm.jpg",
    Featured: true,
  },
  {
    Title: "Terminator 3: Rise of the Machines",
    Description: "A machine from a post-apocalyptic future travels back in time to protect a man and a woman from a terminatrix on a mission to kill them.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Jonathan Mostow", Bio: "American filmmaker known for thriller and action films.", Birth: "November 28, 1961, in New Haven, Connecticut, USA" },
    Actors: ["Arnold Schwarzenegger", "Nick Stahl", "Claire Danes"],
    ImagePath: "https://image.tmdb.org/t/p/w500/rELP2R0UUQFk7hzxwWq9MYQN4WJ.jpg",
    Featured: false,
  },
  {
    Title: "Terminator Salvation",
    Description: "In 2018, a mysterious new weapon in the war against the machines — part man, part machine — comes to terms with his destiny in a chilling confrontation with John Connor.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "McG", Bio: "American filmmaker born Joseph McGinty Nichol, known for action blockbusters.", Birth: "August 9, 1968, in Kalamazoo, Michigan, USA" },
    Actors: ["Christian Bale", "Sam Worthington", "Anton Yelchin"],
    ImagePath: "https://image.tmdb.org/t/p/w500/lhx9bfvmNnJiDRSxeSmXcIgmcwf.jpg",
    Featured: false,
  },
  {
    Title: "Terminator Genisys",
    Description: "When John Connor sends Kyle Reese back to 1984 to protect his mother, an unexpected turn of events creates an altered timeline.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Alan Taylor", Bio: "American filmmaker known for his work on Game of Thrones.", Birth: "October 24, 1959, in Cannes, France" },
    Actors: ["Arnold Schwarzenegger", "Emilia Clarke", "Jai Courtney"],
    ImagePath: "https://image.tmdb.org/t/p/w500/1mOPTb4MNkG5ilEk4lZ4cWnkOqM.jpg",
    Featured: false,
  },

  // ── Toy Story (All 4) ──────────────────────────────────────────────────────
  {
    Title: "Toy Story",
    Description: "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
    Genre: { Name: "Animation", Description: "Films made using animated characters, created for audiences of all ages." },
    Director: { Name: "John Lasseter", Bio: "American animator and filmmaker, the creative force behind Pixar's early classics.", Birth: "January 12, 1957, in Hollywood, California, USA" },
    Actors: ["Tom Hanks", "Tim Allen", "Don Rickles"],
    ImagePath: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPl9KaI82.jpg",
    Featured: false,
  },
  {
    Title: "Toy Story 2",
    Description: "When Woody is stolen by a toy collector, Buzz and his friends vow to rescue him, but Woody finds the idea of immortality in a museum tempting.",
    Genre: { Name: "Animation", Description: "Films made using animated characters, created for audiences of all ages." },
    Director: { Name: "John Lasseter", Bio: "American animator and filmmaker, the creative force behind Pixar's early classics.", Birth: "January 12, 1957, in Hollywood, California, USA" },
    Actors: ["Tom Hanks", "Tim Allen", "Joan Cusack"],
    ImagePath: "https://image.tmdb.org/t/p/w500/84LHpQYGZj6hYFvCvHZnWS7gR3E.jpg",
    Featured: false,
  },
  {
    Title: "Toy Story 3",
    Description: "The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college.",
    Genre: { Name: "Animation", Description: "Films made using animated characters, created for audiences of all ages." },
    Director: { Name: "Lee Unkrich", Bio: "American filmmaker and longtime Pixar collaborator who directed Toy Story 3 and Coco.", Birth: "August 8, 1967, in Chagrin Falls, Ohio, USA" },
    Actors: ["Tom Hanks", "Tim Allen", "Joan Cusack"],
    ImagePath: "https://image.tmdb.org/t/p/w500/AbbXspMOwdvwWZgVP0GSuDfRrJm.jpg",
    Featured: true,
  },
  {
    Title: "Toy Story 4",
    Description: "When a new toy called 'Forky' joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.",
    Genre: { Name: "Animation", Description: "Films made using animated characters, created for audiences of all ages." },
    Director: { Name: "Josh Cooley", Bio: "American filmmaker and animator at Pixar.", Birth: "June 7, 1980, in Pittsburg, California, USA" },
    Actors: ["Tom Hanks", "Tim Allen", "Annie Potts"],
    ImagePath: "https://image.tmdb.org/t/p/w500/w9kR8qbmQ01HwnvK4alvnQ2ca0L.jpg",
    Featured: false,
  },

  // ── Mission: Impossible (Full Series) ─────────────────────────────────────
  {
    Title: "Mission: Impossible",
    Description: "An American agent, under false suspicion of disloyalty, must discover and expose the real spy without the help of his organization.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Brian De Palma", Bio: "American filmmaker known for stylish thriller and crime films.", Birth: "September 11, 1940, in Newark, New Jersey, USA" },
    Actors: ["Tom Cruise", "Jon Voight", "Emmanuelle Béart"],
    ImagePath: "https://image.tmdb.org/t/p/w500/6P5NkHsGKbFArTNlzpV8gE7r8Z8.jpg",
    Featured: false,
  },
  {
    Title: "Mission: Impossible 2",
    Description: "IMF agent Ethan Hunt is sent to Sydney to find and destroy a genetically engineered biological weapon called Chimera.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "John Woo", Bio: "Hong Kong-American filmmaker celebrated for his balletic action sequences.", Birth: "May 1, 1946, in Guangzhou, China" },
    Actors: ["Tom Cruise", "Dougray Scott", "Thandiwe Newton"],
    ImagePath: "https://image.tmdb.org/t/p/w500/pMZzFPVe3gHDWBbqpqQFZf9KGOY.jpg",
    Featured: false,
  },
  {
    Title: "Mission: Impossible III",
    Description: "Ethan Hunt comes face to face with a dangerous and sadistic arms dealer while trying to keep his identity secret in order to protect his fiancée.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "J.J. Abrams", Bio: "American filmmaker and producer behind the Mission: Impossible and Star Trek reboots.", Birth: "June 27, 1966, in New York City, New York, USA" },
    Actors: ["Tom Cruise", "Philip Seymour Hoffman", "Michelle Monaghan"],
    ImagePath: "https://image.tmdb.org/t/p/w500/s8jFf5xCCmFqnHreJPRJCFqKBBd.jpg",
    Featured: false,
  },
  {
    Title: "Mission: Impossible – Ghost Protocol",
    Description: "The IMF is shut down when it's implicated in the bombing of the Kremlin, causing Ethan Hunt and his new team to go rogue.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Brad Bird", Bio: "American filmmaker and animator behind The Incredibles and Ratatouille.", Birth: "September 24, 1957, in Kalispell, Montana, USA" },
    Actors: ["Tom Cruise", "Jeremy Renner", "Simon Pegg"],
    ImagePath: "https://image.tmdb.org/t/p/w500/s5V5bCdJMGJLmBLCsECTRJecGPj.jpg",
    Featured: false,
  },
  {
    Title: "Mission: Impossible – Rogue Nation",
    Description: "Ethan and his team take on their most impossible mission yet, eradicating the Syndicate — an International rogue organization as highly skilled as the IMF.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Christopher McQuarrie", Bio: "American filmmaker and longtime collaborator with Tom Cruise.", Birth: "March 26, 1968, in Princeton, New Jersey, USA" },
    Actors: ["Tom Cruise", "Rebecca Ferguson", "Simon Pegg"],
    ImagePath: "https://image.tmdb.org/t/p/w500/6bFSbOAIcMbcB3mPLn5ItqBhPFM.jpg",
    Featured: false,
  },
  {
    Title: "Mission: Impossible – Fallout",
    Description: "Ethan Hunt and his IMF team race against time to prevent a global catastrophe after a mission gone wrong.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Christopher McQuarrie", Bio: "American filmmaker and longtime collaborator with Tom Cruise.", Birth: "March 26, 1968, in Princeton, New Jersey, USA" },
    Actors: ["Tom Cruise", "Henry Cavill", "Ving Rhames"],
    ImagePath: "https://image.tmdb.org/t/p/w500/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
    Featured: true,
  },
  {
    Title: "Mission: Impossible – Dead Reckoning Part One",
    Description: "Ethan Hunt and his IMF team must track down a dangerous weapon before it falls into the wrong hands.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Christopher McQuarrie", Bio: "American filmmaker and longtime collaborator with Tom Cruise.", Birth: "March 26, 1968, in Princeton, New Jersey, USA" },
    Actors: ["Tom Cruise", "Hayley Atwell", "Simon Pegg"],
    ImagePath: "https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
    Featured: false,
  },

  // ── Jurassic Park / World (Full Series) ───────────────────────────────────
  {
    Title: "Jurassic Park",
    Description: "A pragmatic paleontologist visits a theme park created by a billionaire where cloned dinosaurs roam freely — until things go terribly wrong.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Steven Spielberg", Bio: "American filmmaker and producer widely regarded as one of the most influential directors in cinema history.", Birth: "December 18, 1946, in Cincinnati, Ohio, USA" },
    Actors: ["Sam Neill", "Laura Dern", "Jeff Goldblum"],
    ImagePath: "https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg",
    Featured: true,
  },
  {
    Title: "The Lost World: Jurassic Park",
    Description: "A research team is sent to the Jurassic Park Site B island to study the dinosaurs there while another team approaches with their own agenda.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Steven Spielberg", Bio: "American filmmaker and producer widely regarded as one of the most influential directors in cinema history.", Birth: "December 18, 1946, in Cincinnati, Ohio, USA" },
    Actors: ["Jeff Goldblum", "Julianne Moore", "Pete Postlethwaite"],
    ImagePath: "https://image.tmdb.org/t/p/w500/gFxtdSPASoG8tBVTBCaFMSPrDM8.jpg",
    Featured: false,
  },
  {
    Title: "Jurassic Park III",
    Description: "A decidedly odd couple with ulterior motives convince Dr. Alan Grant to go to Isla Sorna for a holiday, only to discover they are not alone.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Joe Johnston", Bio: "American filmmaker and visual effects artist.", Birth: "May 13, 1950, in Austin, Texas, USA" },
    Actors: ["Sam Neill", "William H. Macy", "Téa Leoni"],
    ImagePath: "https://image.tmdb.org/t/p/w500/lzmQCPCOBCxNVMPNWO34r5ATJRL.jpg",
    Featured: false,
  },
  {
    Title: "Jurassic World",
    Description: "A new theme park is built on the original site of Jurassic Park. When a genetically engineered hybrid dinosaur escapes, a former dinosaur trainer must step up.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Colin Trevorrow", Bio: "American filmmaker known for Safety Not Guaranteed.", Birth: "September 13, 1976, in San Francisco, California, USA" },
    Actors: ["Chris Pratt", "Bryce Dallas Howard", "Vincent D'Onofrio"],
    ImagePath: "https://image.tmdb.org/t/p/w500/dkMD5qlogeRMiEixC4YNPUvax2T.jpg",
    Featured: false,
  },
  {
    Title: "Jurassic World: Fallen Kingdom",
    Description: "When the island's dormant volcano begins roaring to life, Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction-level event.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "J.A. Bayona", Bio: "Spanish filmmaker known for A Monster Calls and The Impossible.", Birth: "April 9, 1975, in Barcelona, Spain" },
    Actors: ["Chris Pratt", "Bryce Dallas Howard", "Rafe Spall"],
    ImagePath: "https://image.tmdb.org/t/p/w500/fgMjGAB3T5V9XFVbOrO7wMakqJN.jpg",
    Featured: false,
  },
  {
    Title: "Jurassic World Dominion",
    Description: "Four years after the destruction of Isla Nublar, dinosaurs now live and hunt alongside humans all over the world. This fragile balance will reshape the future of the planet.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Colin Trevorrow", Bio: "American filmmaker known for Safety Not Guaranteed.", Birth: "September 13, 1976, in San Francisco, California, USA" },
    Actors: ["Chris Pratt", "Bryce Dallas Howard", "Sam Neill"],
    ImagePath: "https://image.tmdb.org/t/p/w500/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
    Featured: false,
  },

  // ── James Bond (Craig Era) ────────────────────────────────────────────────
  {
    Title: "Casino Royale",
    Description: "Armed with a licence to kill, secret agent James Bond sets out on his first mission as 007, where he must defeat a private banker funding terrorists.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Martin Campbell", Bio: "New Zealand filmmaker who directed two Bond reboots: GoldenEye and Casino Royale.", Birth: "October 24, 1943, in Hastings, New Zealand" },
    Actors: ["Daniel Craig", "Judi Dench", "Eva Green"],
    ImagePath: "https://image.tmdb.org/t/p/w500/oEQLlqvvZFDOFahYTfzu1d3GPbP.jpg",
    Featured: true,
  },
  {
    Title: "Quantum of Solace",
    Description: "James Bond descends into mystery as he tries to stop a mysterious organization from eliminating a country's most valuable resource.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Marc Forster", Bio: "German-Swiss filmmaker known for Monster's Ball and Quantum of Solace.", Birth: "November 30, 1969, in Illertissen, Bavaria, Germany" },
    Actors: ["Daniel Craig", "Olga Kurylenko", "Judi Dench"],
    ImagePath: "https://image.tmdb.org/t/p/w500/8fLaHMp7cEFd7xWHQY8NtgZrDdv.jpg",
    Featured: false,
  },
  {
    Title: "Skyfall",
    Description: "Bond's loyalty to M is tested when her past comes back to haunt her, as MI6 comes under attack from a mysterious figure.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Sam Mendes", Bio: "British filmmaker and Academy Award winner for American Beauty.", Birth: "August 1, 1965, in Reading, Berkshire, England, UK" },
    Actors: ["Daniel Craig", "Javier Bardem", "Judi Dench"],
    ImagePath: "https://image.tmdb.org/t/p/w500/xa2fPUMGfPYmQxnFnzJGHMB0UAT.jpg",
    Featured: true,
  },
  {
    Title: "Spectre",
    Description: "A cryptic message from Bond's past sends him on a trail to uncover a sinister organization called SPECTRE.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Sam Mendes", Bio: "British filmmaker and Academy Award winner for American Beauty.", Birth: "August 1, 1965, in Reading, Berkshire, England, UK" },
    Actors: ["Daniel Craig", "Christoph Waltz", "Léa Seydoux"],
    ImagePath: "https://image.tmdb.org/t/p/w500/hE24GYddaxB9MVZf1p4QPQYEPgK.jpg",
    Featured: false,
  },
  {
    Title: "No Time to Die",
    Description: "Bond has left active service and is enjoying a tranquil life in Jamaica before his old CIA friend Felix Leiter shows up and lures him back into action.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Cary Joji Fukunaga", Bio: "American filmmaker known for Beasts of No Nation and True Detective.", Birth: "July 10, 1977, in Oakland, California, USA" },
    Actors: ["Daniel Craig", "Ana de Armas", "Rami Malek"],
    ImagePath: "https://image.tmdb.org/t/p/w500/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
    Featured: false,
  },

  // ── The Alien Saga ────────────────────────────────────────────────────────
  {
    Title: "Alien",
    Description: "After a space merchant vessel receives an unknown transmission as a distress call, one of the crew is attacked by a mysterious life form.",
    Genre: { Name: "Horror", Description: "Films designed to frighten and disturb the audience through dread and suspense." },
    Director: { Name: "Ridley Scott", Bio: "British filmmaker celebrated for Alien, Blade Runner, Gladiator, and The Martian.", Birth: "November 30, 1937, in South Shields, County Durham, England, UK" },
    Actors: ["Sigourney Weaver", "Tom Skerritt", "John Hurt"],
    ImagePath: "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    Featured: true,
  },
  {
    Title: "Aliens",
    Description: "Fifty-seven years after surviving an apocalyptic attack aboard her space vessel, Ellen Ripley is sent back to the planet where her crew encountered the hostile alien creatures.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "James Cameron", Bio: "Canadian filmmaker known for Titanic, Avatar, and the Terminator franchise.", Birth: "August 16, 1954, in Kapuskasing, Ontario, Canada" },
    Actors: ["Sigourney Weaver", "Michael Biehn", "Bill Paxton"],
    ImagePath: "https://image.tmdb.org/t/p/w500/r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg",
    Featured: true,
  },
  {
    Title: "Alien 3",
    Description: "After her last encounter, Ellen Ripley crash-lands on Fiorina 161, a maximum security prison. When a mysterious creature kills off the prisoners, Ripley realizes she has brought along an unwanted visitor.",
    Genre: { Name: "Horror", Description: "Films designed to frighten and disturb the audience through dread and suspense." },
    Director: { Name: "David Fincher", Bio: "American filmmaker known for Fight Club, Se7en, Zodiac, and The Social Network.", Birth: "August 28, 1962, in Denver, Colorado, USA" },
    Actors: ["Sigourney Weaver", "Charles S. Dutton", "Charles Dance"],
    ImagePath: "https://image.tmdb.org/t/p/w500/p4G2M8uqKuvl9qSJQiLBGMO3VJn.jpg",
    Featured: false,
  },
  {
    Title: "Alien: Resurrection",
    Description: "200 years after her death, Ellen Ripley is revived as a powerful human/alien hybrid clone who continues to be stalked by these creatures.",
    Genre: { Name: "Horror", Description: "Films designed to frighten and disturb the audience through dread and suspense." },
    Director: { Name: "Jean-Pierre Jeunet", Bio: "French filmmaker known for Amélie and City of Lost Children.", Birth: "September 3, 1953, in Roanne, Loire, France" },
    Actors: ["Sigourney Weaver", "Winona Ryder", "Ron Perlman"],
    ImagePath: "https://image.tmdb.org/t/p/w500/pF2T2Rj7RlqcTUmGXE15InepNyU.jpg",
    Featured: false,
  },
  {
    Title: "Prometheus",
    Description: "Following clues to the origin of mankind, a team travels to the darkest corners of the universe to discover the engineers behind humanity's creation — and a terrifying threat.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Ridley Scott", Bio: "British filmmaker celebrated for Alien, Blade Runner, Gladiator, and The Martian.", Birth: "November 30, 1937, in South Shields, County Durham, England, UK" },
    Actors: ["Noomi Rapace", "Michael Fassbender", "Charlize Theron"],
    ImagePath: "https://image.tmdb.org/t/p/w500/qknaaTLdlO0aRQAJXVYJMDjpMBO.jpg",
    Featured: false,
  },
  {
    Title: "Alien: Covenant",
    Description: "The crew of the colony ship Covenant, bound for a remote planet on the far side of the galaxy, discovers what they think is an uncharted paradise — but is actually a dark, dangerous world.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Ridley Scott", Bio: "British filmmaker celebrated for Alien, Blade Runner, Gladiator, and The Martian.", Birth: "November 30, 1937, in South Shields, County Durham, England, UK" },
    Actors: ["Michael Fassbender", "Katherine Waterston", "Billy Crudup"],
    ImagePath: "https://image.tmdb.org/t/p/w500/soid7GpGlbFEBLm0x9E2q8CijBf.jpg",
    Featured: false,
  },

  // ── The Hunger Games (All 4) ──────────────────────────────────────────────
  {
    Title: "The Hunger Games",
    Description: "Katniss Everdeen voluntarily takes her younger sister's place in a televised death match between teenagers from each district of the dystopian nation of Panem.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Gary Ross", Bio: "American filmmaker and screenwriter known for Pleasantville and Seabiscuit.", Birth: "November 3, 1956, in Los Angeles, California, USA" },
    Actors: ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth"],
    ImagePath: "https://image.tmdb.org/t/p/w500/samTF8sOCCQNqaFcSQiCxTrqkfE.jpg",
    Featured: false,
  },
  {
    Title: "The Hunger Games: Catching Fire",
    Description: "After winning the 74th Hunger Games, Katniss and Peeta are forced into a special edition of the Games featuring past victors.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Francis Lawrence", Bio: "American filmmaker known for the latter three Hunger Games films.", Birth: "March 26, 1972, in Vienna, Austria" },
    Actors: ["Jennifer Lawrence", "Josh Hutcherson", "Philip Seymour Hoffman"],
    ImagePath: "https://image.tmdb.org/t/p/w500/jTBBUQsOuOtqeymNSYjflkCmHoE.jpg",
    Featured: false,
  },
  {
    Title: "The Hunger Games: Mockingjay – Part 1",
    Description: "Katniss Everdeen is in District 13 after she shatters the games forever. Under the leadership of President Coin, Katniss becomes the symbol of rebellion — the Mockingjay.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Francis Lawrence", Bio: "American filmmaker known for the latter three Hunger Games films.", Birth: "March 26, 1972, in Vienna, Austria" },
    Actors: ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth"],
    ImagePath: "https://image.tmdb.org/t/p/w500/gSFqnMPADZOz7gUVSSq0qzLhxEf.jpg",
    Featured: false,
  },
  {
    Title: "The Hunger Games: Mockingjay – Part 2",
    Description: "As the war of Panem escalates to the destruction of other districts, Katniss Everdeen, the reluctant leader of the rebellion, must bring it all to an end.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Francis Lawrence", Bio: "American filmmaker known for the latter three Hunger Games films.", Birth: "March 26, 1972, in Vienna, Austria" },
    Actors: ["Jennifer Lawrence", "Josh Hutcherson", "Donald Sutherland"],
    ImagePath: "https://image.tmdb.org/t/p/w500/c1sCIEsiFOLJNfS16FcxQFMqo1X.jpg",
    Featured: false,
  },

  // ── Standalone Classics ───────────────────────────────────────────────────
  {
    Title: "The Shawshank Redemption",
    Description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    Genre: { Name: "Drama", Description: "Character-driven stories exploring the human condition." },
    Director: { Name: "Frank Darabont", Bio: "American filmmaker known for adapting Stephen King's works to film.", Birth: "January 28, 1959, in Montbeliard, France" },
    Actors: ["Tim Robbins", "Morgan Freeman"],
    ImagePath: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    Featured: true,
  },
  {
    Title: "The Godfather",
    Description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    Genre: { Name: "Crime", Description: "Films centered on criminal activities and their consequences." },
    Director: { Name: "Francis Ford Coppola", Bio: "American filmmaker celebrated for the Godfather trilogy and Apocalypse Now.", Birth: "April 7, 1939, in Detroit, Michigan, USA" },
    Actors: ["Marlon Brando", "Al Pacino", "James Caan"],
    ImagePath: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLlegkAzin1x.jpg",
    Featured: true,
  },
  {
    Title: "The Godfather Part II",
    Description: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
    Genre: { Name: "Crime", Description: "Films centered on criminal activities and their consequences." },
    Director: { Name: "Francis Ford Coppola", Bio: "American filmmaker celebrated for the Godfather trilogy and Apocalypse Now.", Birth: "April 7, 1939, in Detroit, Michigan, USA" },
    Actors: ["Al Pacino", "Robert De Niro", "Diane Keaton"],
    ImagePath: "https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    Featured: false,
  },
  {
    Title: "Pulp Fiction",
    Description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    Genre: { Name: "Crime", Description: "Films centered on criminal activities and their consequences." },
    Director: { Name: "Quentin Tarantino", Bio: "American filmmaker known for non-linear narratives and sharp dialogue.", Birth: "March 27, 1963, in Knoxville, Tennessee, USA" },
    Actors: ["John Travolta", "Samuel L. Jackson", "Uma Thurman"],
    ImagePath: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    Featured: true,
  },
  {
    Title: "Interstellar",
    Description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Christopher Nolan", Bio: "British-American filmmaker renowned for complex, cerebral blockbusters.", Birth: "July 30, 1970, in London, England, UK" },
    Actors: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    ImagePath: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lZtvFaT71Ae.jpg",
    Featured: true,
  },
  {
    Title: "Inception",
    Description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Christopher Nolan", Bio: "British-American filmmaker renowned for complex, cerebral blockbusters.", Birth: "July 30, 1970, in London, England, UK" },
    Actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    ImagePath: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    Featured: true,
  },
  {
    Title: "Forrest Gump",
    Description: "The presidencies of Kennedy and Johnson, Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with a below-average IQ.",
    Genre: { Name: "Drama", Description: "Character-driven stories exploring the human condition." },
    Director: { Name: "Robert Zemeckis", Bio: "American filmmaker known for Back to the Future, Forrest Gump, and Cast Away.", Birth: "May 14, 1952, in Chicago, Illinois, USA" },
    Actors: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    ImagePath: "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    Featured: true,
  },
  {
    Title: "Schindler's List",
    Description: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    Genre: { Name: "Drama", Description: "Character-driven stories exploring the human condition." },
    Director: { Name: "Steven Spielberg", Bio: "American filmmaker and producer widely regarded as one of the most influential directors in cinema history.", Birth: "December 18, 1946, in Cincinnati, Ohio, USA" },
    Actors: ["Liam Neeson", "Ralph Fiennes", "Ben Kingsley"],
    ImagePath: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    Featured: true,
  },
  {
    Title: "Parasite",
    Description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    Genre: { Name: "Drama", Description: "Character-driven stories exploring the human condition." },
    Director: { Name: "Bong Joon-ho", Bio: "South Korean filmmaker and Academy Award winner for Parasite.", Birth: "September 14, 1969, in Daegu, South Korea" },
    Actors: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    ImagePath: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    Featured: true,
  },
  {
    Title: "The Silence of the Lambs",
    Description: "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
    Genre: { Name: "Thriller", Description: "Suspenseful films designed to keep audiences on edge." },
    Director: { Name: "Jonathan Demme", Bio: "American filmmaker and Academy Award winner for The Silence of the Lambs.", Birth: "February 22, 1944, in Baldwin, New York, USA" },
    Actors: ["Jodie Foster", "Anthony Hopkins"],
    ImagePath: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    Featured: true,
  },
  {
    Title: "Gladiator",
    Description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    Genre: { Name: "Action", Description: "High-energy films featuring physical feats and heroics." },
    Director: { Name: "Ridley Scott", Bio: "British filmmaker celebrated for Alien, Blade Runner, Gladiator, and The Martian.", Birth: "November 30, 1937, in South Shields, County Durham, England, UK" },
    Actors: ["Russell Crowe", "Joaquin Phoenix"],
    ImagePath: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    Featured: false,
  },
  {
    Title: "Fight Club",
    Description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much, much more.",
    Genre: { Name: "Drama", Description: "Character-driven stories exploring the human condition." },
    Director: { Name: "David Fincher", Bio: "American filmmaker known for Fight Club, Se7en, Zodiac, and The Social Network.", Birth: "August 28, 1962, in Denver, Colorado, USA" },
    Actors: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    ImagePath: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    Featured: false,
  },
  {
    Title: "The Good, the Bad and the Ugly",
    Description: "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
    Genre: { Name: "Western", Description: "Films set in the American frontier era, exploring themes of honor and survival." },
    Director: { Name: "Sergio Leone", Bio: "Italian filmmaker and pioneer of the Spaghetti Western genre.", Birth: "January 3, 1929, in Rome, Italy" },
    Actors: ["Clint Eastwood", "Lee Van Cleef", "Eli Wallach"],
    ImagePath: "https://image.tmdb.org/t/p/w500/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    Featured: false,
  },
  {
    Title: "Django Unchained",
    Description: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
    Genre: { Name: "Western", Description: "Films set in the American frontier era, exploring themes of honor and survival." },
    Director: { Name: "Quentin Tarantino", Bio: "American filmmaker known for non-linear narratives and sharp dialogue.", Birth: "March 27, 1963, in Knoxville, Tennessee, USA" },
    Actors: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio"],
    ImagePath: "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWAb8X.jpg",
    Featured: false,
  },
  {
    Title: "The Lion King",
    Description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    Genre: { Name: "Animation", Description: "Films made using animated characters, created for audiences of all ages." },
    Director: { Name: "Roger Allers", Bio: "American animator and director of The Lion King.", Birth: "June 29, 1949, in Rye, New York, USA" },
    Actors: ["Matthew Broderick", "James Earl Jones", "Jeremy Irons"],
    ImagePath: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    Featured: true,
  },
  {
    Title: "The Martian",
    Description: "During a Mars mission, astronaut Mark Watney is presumed dead after a fierce storm and left behind. Stranded on Mars, he must find a way to signal that he is alive.",
    Genre: { Name: "Science Fiction", Description: "Speculative fiction exploring futuristic concepts, space, and technology." },
    Director: { Name: "Ridley Scott", Bio: "British filmmaker celebrated for Alien, Blade Runner, Gladiator, and The Martian.", Birth: "November 30, 1937, in South Shields, County Durham, England, UK" },
    Actors: ["Matt Damon", "Jessica Chastain", "Kristen Wiig"],
    ImagePath: "https://image.tmdb.org/t/p/w500/5aGhaIHYuQbqlHWvWYqMCnj40y2.jpg",
    Featured: false,
  },
  {
    Title: "Get Out",
    Description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception grows into dread.",
    Genre: { Name: "Horror", Description: "Films designed to frighten and disturb the audience through dread and suspense." },
    Director: { Name: "Jordan Peele", Bio: "American comedian and filmmaker known for Get Out and Us.", Birth: "February 21, 1979, in New York City, New York, USA" },
    Actors: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford"],
    ImagePath: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    Featured: false,
  },
  {
    Title: "The Grand Budapest Hotel",
    Description: "A writer encounters the owner of an aging European hotel and learns of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.",
    Genre: { Name: "Comedy", Description: "Films intended to entertain and amuse through humor and wit." },
    Director: { Name: "Wes Anderson", Bio: "American filmmaker known for his distinctive symmetrical visual style.", Birth: "May 1, 1969, in Houston, Texas, USA" },
    Actors: ["Ralph Fiennes", "Tony Revolori", "Saoirse Ronan"],
    ImagePath: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    Featured: false,
  },
];

async function seedDatabase() {
  try {
    console.log("Connecting to MongoDB...");
    await mongoose.connect(process.env.CONNECTION_URI);
    console.log("Connected to MongoDB");

    console.log(`Upserting ${movies.length} movies (safe to re-run)...`);

    let inserted = 0;

    for (const movie of movies) {
      const existing = await Movie.findOne({ Title: movie.Title });
      await Movie.findOneAndUpdate(
        { Title: movie.Title },
        { $set: movie },
        { upsert: true, new: true }
      );
      if (!existing) inserted++;
    }

    console.log(`Done! Inserted ${inserted} new, updated ${movies.length - inserted} existing.`);

    await mongoose.connection.close();
    console.log("Database connection closed");
    process.exit(0);
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
}

seedDatabase();
